### ISSUE TITLE
Some corrections for the Stoned virus description

### ISSUE THREAD

**Issue by tkchia** [topherCantrell/computerarcheology#9]
Hello @topherCantrell,

Nice work on your Computer Archeology web site!

In your [description of the Stoned virus](http://www.computerarcheology.com/Virus/Stoned/), you state that, "fixed-disks have 1K sectors (twice as large as the sectors on a floppy)".

That is not correct --- fixed disks _do_ have ½KiB sectors, just like in floppy disks, at least at the `int 0x13` level.  There is a description of the hard disk's master boot sector format in [Ralf Brown's Interrupt List](https://www.cs.cmu.edu/~ralf/files.html) (specifically in [Table #00650](http://www.delorie.com/djgpp/doc/rbinter/it/50/6.html), under the description for `int 0x19`).  The primary partition table occupies just 64 bytes out of the boot sector's 512 bytes, and is followed by the `0x55 0xAA` boot record signature.

(A corollary is that it is now unclear why the virus would need to copy `0x242` bytes and not just `0x42` bytes, or why it needs to reserve 2KiB of conventional memory for itself.)

Another issue I spotted was that some parts of the disassembly appeared as hyperlinks when they should probably just be in square brackets.  E.g.

> `CMP     AX,`[`DI`](http://www.computerarcheology.com/Virus/Stoned/DI)

should probably be

> `CMP     AX,[DI]`

Thank you!

**Comment by topherCantrell** [comment]
Oh wow! Thanks for the great information! I will correct the content and give you full credit.

**Comment by tkchia** [comment]
Hello @topherCantrell ,

Thank you very much!  I am just trying to contribute when I can.

**Comment by topherCantrell** [comment]
The Stoned virus disassembly is OOOLLLDDDDDDD. I am revisiting it now to
give it some new love and correct the sector-size mistake you pointed out.
Thanks again for that. I'll run it by you shortly.

**Comment by topherCantrell** [comment]
I think I got the text fixed! Thanks again. I added a blurb at the bottom noting your correction.

**Comment by tkchia** [comment]
Hello @topherCantrell ,

Thank you!  I look forward to seeing it live. ☺
